# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 690b25d8b1d02fbd63f87eadcf006d724b1ce603d5cd8be6a6bedd1d7fa6c5b9f910afc25b47b472efe1c30e564981614470fccc08144285603ee3f735853816

test:
  secret_key_base: 71544e4d449b53b65717bfebee40459ca330ae81f5e3097639a9e48a8afa55de11311d6f530cf5b98eff87387a3240558588284e47627265e54d41e1c5f5eda9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
